[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_APPSCRIPT_URL = "https://script.google.com/macros/s/AKfycbzpi6ukC0MhjpfLmZw1HWpGWOYK07P99aDgwsbZn1TvU2AwomKtog1unkxgpd_9B6Z1Xw/exec"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
